///<reference path="../../node_modules/tsd-goalazo-models/models.d.ts"/>
///<reference path="../../typings/q/Q.d.ts"/>


import ICompetitionSeries = goalazo.ICompetitionSeries;
import Promise = Q.Promise;

import Q = require('q');
import Models from '../../models/index';
import {ICompetitionSeriesInstance} from "../../typings/custom/models";
import IUser = goalazo.IUser;
import ICompetition = goalazo.ICompetition;
import {Model} from "sequelize";
import {IUserInstance} from "../../typings/custom/models";

export class UserRepoUno {

    getUser(name: string): Promise<IUserInstance> {

        return Q.when()
            .then(() => Models.User.find({
                where: {
                    name: name
                }
            }));
    }

    setUser(isAutoGenerated, name: string, password?: string): Promise<IUserInstance> {

        return Q.when()
            .then(() => Models.User.create({
                name,
                password,
                isAutoGenerated
            }))
    }
}
