///<reference path="../../node_modules/tsd-goalazo-models/models.d.ts"/>
///<reference path="../../typings/q/Q.d.ts"/>
var Q = require('q');
var index_1 = require('../../models/index');
var UserRepoUno = (function () {
    function UserRepoUno() {
    }
    UserRepoUno.prototype.getUser = function (name) {
        return Q.when()
            .then(function () { return index_1["default"].User.find({
            where: {
                name: name
            }
        }); });
    };
    UserRepoUno.prototype.setUser = function (isAutoGenerated, name, password) {
        return Q.when()
            .then(function () { return index_1["default"].User.create({
            name: name,
            password: password,
            isAutoGenerated: isAutoGenerated
        }); });
    };
    return UserRepoUno;
})();
exports.UserRepoUno = UserRepoUno;
//# sourceMappingURL=UserRepoUno.js.map