import {Table} from "../orm/annotations/Table";
import {Column} from "../orm/annotations/Column";
import {PrimaryKey} from "../orm/annotations/PrimaryKey";
import {Model} from "../orm/models/Model";
import {Default} from "../orm/annotations/Default";
import {DataType} from "../orm/models/DataType";
import {DefaultScope} from "../orm/annotations/DefaultScope";
import {AutoIncrement} from "../orm/annotations/AutoIncrement";
import jwt = require('jsonwebtoken');
import {config} from "../config";
import {Scopes} from "../orm/annotations/Scopes";

@Table
@DefaultScope({attributes: ['id', 'evcoId', 'code', 'isAutoGenerated', 'languageCode']})
export class User extends Model<User> implements IUser {

  @Column
  @PrimaryKey
  @AutoIncrement
  id: number;

  @Column
  evcoId: string;

  @Column
  code: string;

  @Column
  password: string;

  @Column
  isAutoGenerated: boolean;

  @Column
  @Default(DataType.NOW)
  registrationDate: Date;

  @Column
  languageCode: string;

  @Column({
    type: DataType.VIRTUAL
  })
  token: string;
  
}
